import StyleDictionary from 'style-dictionary';
import { readFile, writeFile, rm } from 'node:fs/promises';

const CSS_DIR = 'dist/css';

// ---------------------------------------------------------------------------
// Custom name transform.
// Drops the leading group segment (`base` / `components`) so the CSS variable
// names match shadcn exactly at the base layer and extend predictably for
// components:
//   base.input            -> --input
//   base.card-foreground  -> --card-foreground
//   components.input.bg   -> --input-bg
// ---------------------------------------------------------------------------
StyleDictionary.registerTransform({
  name: 'name/webmcpui',
  type: 'name',
  transform: (token) => token.path.slice(1).join('-'),
});

// Values in tokens/*.json are already valid CSS (oklch strings, rem/px units),
// so the only transform we need is the name. One group per output language.
StyleDictionary.registerTransformGroup({
  name: 'webmcpui/css',
  transforms: ['name/webmcpui'],
});
StyleDictionary.registerTransformGroup({
  name: 'webmcpui/js',
  transforms: ['name/webmcpui'],
});

// JS/TS exports. Our token names are kebab-case (e.g. `card-foreground`),
// which aren't valid `export const` identifiers, so we emit a keyed object
// instead — keys map 1:1 to the CSS variable names.
StyleDictionary.registerFormat({
  name: 'javascript/webmcpui',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map(
      (t) => `  '${t.name}': ${JSON.stringify(t.value ?? t.$value)},`,
    );
    return (
      '// Generated by Style Dictionary. Do not edit by hand.\n' +
      'export const tokens = {\n' +
      lines.join('\n') +
      '\n};\n\nexport default tokens;\n'
    );
  },
});
StyleDictionary.registerFormat({
  name: 'typescript/webmcpui',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((t) => `  '${t.name}': string;`);
    return (
      '// Generated by Style Dictionary. Do not edit by hand.\n' +
      'export declare const tokens: {\n' +
      lines.join('\n') +
      '\n};\nexport default tokens;\n'
    );
  },
});

// Figma variables import: resolved values keyed by slash path (group prefix
// dropped, matching the CSS variable names). Token Studio / the Figma Variables
// importer consume this; names mirror the CSS vars so the two sides can't drift.
StyleDictionary.registerFormat({
  name: 'json/figma',
  format: ({ dictionary }) => {
    const out = {};
    for (const token of dictionary.allTokens) {
      const key = token.path.slice(1).join('/');
      out[key] = {
        value: token.value ?? token.$value,
        type: token.$type ?? token.type,
      };
    }
    return JSON.stringify(out, null, 2) + '\n';
  },
});

// Light theme + component tokens -> :root, plus JS/TS/Figma outputs.
const light = new StyleDictionary({
  source: [
    'tokens/base/color.json',
    'tokens/base/dimension.json',
    'tokens/components/**/*.json',
  ],
  platforms: {
    css: {
      transformGroup: 'webmcpui/css',
      buildPath: `${CSS_DIR}/`,
      files: [
        {
          destination: '_root.css',
          format: 'css/variables',
          options: { selector: ':root', outputReferences: true },
        },
      ],
    },
    js: {
      transformGroup: 'webmcpui/js',
      buildPath: 'dist/js/',
      files: [
        { destination: 'tokens.js', format: 'javascript/webmcpui' },
        { destination: 'tokens.d.ts', format: 'typescript/webmcpui' },
      ],
    },
    figma: {
      transformGroup: 'webmcpui/js',
      buildPath: 'dist/figma/',
      files: [{ destination: 'tokens.json', format: 'json/figma' }],
    },
  },
});

// Dark theme overrides only -> .dark
const dark = new StyleDictionary({
  source: ['tokens/base/color.dark.json'],
  platforms: {
    css: {
      transformGroup: 'webmcpui/css',
      buildPath: `${CSS_DIR}/`,
      files: [
        {
          destination: '_dark.css',
          format: 'css/variables',
          options: { selector: '.dark' },
        },
      ],
    },
  },
});

await light.buildAllPlatforms();
await dark.buildAllPlatforms();

// Merge the two CSS partials into a single tokens.css (:root + .dark) and
// clean up the partials.
const root = await readFile(`${CSS_DIR}/_root.css`, 'utf8');
const darkCss = await readFile(`${CSS_DIR}/_dark.css`, 'utf8');
const banner =
  '/**\n * webmcpui design tokens — generated by Style Dictionary.\n' +
  ' * Source of truth: tokens/*.json. Do not edit by hand.\n */\n\n';
await writeFile(`${CSS_DIR}/tokens.css`, banner + root + '\n' + darkCss);
await rm(`${CSS_DIR}/_root.css`);
await rm(`${CSS_DIR}/_dark.css`);

console.log('✓ tokens built: dist/css/tokens.css, dist/js/tokens.{js,d.ts}, dist/figma/tokens.json');
